[features]
seeds = false
[programs.devnet]
magiceden_clone = "5Ui7xAECN7ahHJMwQPQLXLnzCd1Wf8MLBv46zztcBFE9"

[registry]
url = "https://anchor.projectserum.com"

[provider]
#cluster = "localnet"
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
start = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 app/start.ts"
